name: demo_marvel
description: "Demo Marvel StratPlus"

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  get_storage: ^2.1.1
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true

  assets:
    - .env.marvel
    - assets/
    - assets/fonts/
    - assets/images/

  fonts:
    - family: Marvel
      fonts:
        - asset: assets/fonts/Marvel-Regular.ttf
